source :rubygems

gem 'cramp'

# Async webserver for running a cramp application
gem 'thin'

# Rack based routing
gem 'http_router'

# For async Active Record models
<% if active_record? -%>
gem 'mysql2', '~> 0.2.7'
gem 'activerecord'
<% else -%>
# gem 'mysql2', '~> 0.2.7'
# gem 'activerecord'
<% end -%>

# Using Fibers + async callbacks to emulate synchronous programming
# gem 'em-synchrony'
