source :rubygems

gem 'cramp'

# Async webserver for running a cramp application
gem 'thin'

# Rack based routing
gem 'http_router'

# For async Active Record models
<% if active_record? -%>
gem 'mysql2', '~> 0.2.11'
gem 'activerecord'
<% else -%>
# gem 'mysql2', '~> 0.2.11'
# gem 'activerecord'
<% end -%>

# Using Fibers + async callbacks to emulate synchronous programming
# gem 'em-synchrony'

# Generic interface to multiple Ruby template engines - https://github.com/rtomayko/tilt
# gem 'tilt'
